### ISSUE TITLE
Accessibility: Tlačidlo pre zatvorenie dialógového okna nemá menovku

### ISSUE THREAD

**Issue by rraddatch** [slovensko-digital/autogram-extension#104]
Tlačidlo pre zatvorenie dialógového okna nemá menovku.
Nevidiaci používateľ nevie aký je účel tohto tlačidla.

Riešenie:
```html
<button aria-label="Zatvoriť okno" class="close">
     <span class="sr-only">Zatvoriť okno</span>
     <svg role="img" aria-hidden="true">...</svg>
     ...
</button>
```
```css
.sr-only {
	border: 0 !important;
	clip: rect(1px, 1px, 1px, 1px) !important;
	-webkit-clip-path: inset(50%) !important;
		clip-path: inset(50%) !important;
	height: 1px !important;
	margin: -1px !important;
	overflow: hidden !important;
	padding: 0 !important;
	position: absolute !important;
	width: 1px !important;
	white-space: nowrap !important;
}
```
![2024-11-16_14h53_04](https://github.com/user-attachments/assets/99ca00b6-dc66-4db6-9867-5ac8b5ecca7e)
![2024-11-16_14h58_03](https://github.com/user-attachments/assets/1130dad7-e611-4527-a7bb-77b427500898)
